language: python
python: 2.7
env:
  - TARGET=test
  - TARGET=coverage.sh
install:
  - easy_install --version
  - pip install setuptools==7.0
  - sudo apt-get -qq install libfreetype6-dev liblcms1-dev gettext
  - mkdir -p buildout-cache/{eggs,downloads}
  - python bootstrap.py -c travis.cfg
  - bin/buildout -Nc travis.cfg
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - bin/test
  - bin/coverage run bin/test
after_success:
  - pip install coveralls==0.5
  - coveralls
notifications:
  irc:
      - ""
  email:
      - devs@imio.be
