language: python

cache:
  pip: true
  directories:
    - buildout-cache/downloads
    - buildout-cache/eggs

python: 2.7

env:
  - TARGET=test
  - TARGET=coverage.sh

install:
  - easy_install --version
  - mkdir -p buildout-cache/{eggs,downloads}
  - sudo apt-get -qq install libfreetype6-dev gettext
  - mkdir -p buildout-cache/{eggs,downloads}
  - python bootstrap.py --buildout-version=2.13.1 --setuptools-version=38.2.4
  - bin/buildout -Nc travis.cfg
  - bin/translation-manage -c

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
  - bin/test
  - bin/createcoverage

after_success:
  - pip install coveralls==0.5
  - coveralls

notifications:
  irc:
      - ""
  email:
      - devs@imio.be
