language: python

cache:
  pip: true
  directories:
    - buildout-cache/downloads
    - buildout-cache/eggs

python: 2.7

env:
  - TARGET=test
  - TARGET=coverage.sh

install:
  - easy_install --version
  - mkdir -p buildout-cache/{eggs,downloads}
  - sudo apt-get -qq install libfreetype6-dev gettext
  - mkdir -p buildout-cache/{eggs,downloads}
  - python bootstrap.py
  - bin/buildout -c travis.cfg

script:
  - bin/test
  - bin/createcoverage

after_success:
  - pip install coveralls==0.5
  - coveralls

notifications:
  email:
      - devs@imio.be
